<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Stride.CommunityToolkit.Windows" Version="1.0.0-preview.62" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StrideTerrainGeneration.Core\StrideTerrainGeneration.Core.csproj" />
  </ItemGroup>

</Project>
