# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on: [push]

jobs:
  build:    
    runs-on: windows-latest
    env:
      CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      shell: pwsh
      run: |
        $dotnetParams = @(
          "--no-restore",
          "/m:1",
          "--configuration", "$env:CONFIGURATION"
        )

        dotnet build @dotnetParams

    - name: Test
      shell: pwsh
      run: |
        $dotnetParams = @(
          "--no-build",
          "--configuration", "$env:CONFIGURATION",
          "--verbosity", "normal",
          "--collect:XPlat Code Coverage",
          "--logger", "trx",
          "--results-directory", "TestResults"
        )

        dotnet test @dotnetParams

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        name: Unit Tests            # Name of the check run which will be created
        path: TestResults/**/*.trx        
        reporter: dotnet-trx        # Format of test results

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.5.1
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coverage'
        reporttypes: 'Markdown;MarkdownAssembliesSummary;MarkdownSummaryGithub;MarkdownDeltaSummary'

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport # Artifact name        
        path: coverage 
        
    - name: Benchmark
      shell: pwsh
      run: |
        $dotnetParams = @(
          "--no-build",
          "--configuration", "$env:CONFIGURATION",
          "--project", "benchmarks/StrideTerrainGeneration.Benchmarks/StrideTerrainGeneration.Benchmarks.csproj",
          "--filter", "*",
          "--verbosity", "normal"
        )
        dotnet run @dotnetParams