# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on: [push]

jobs:
  build:    
    runs-on: windows-latest
    env:
      CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
        $dotnetParams = @(
          "--no-restore",
          "/m:1",
          "--configuration", "${CONFIGURATION}"
        )

        dotnet build @dotnetParams

    - name: Test
      run: |
        $dotnetParams = @(
          "--no-build",
          "--configuration", "${CONFIGURATION}",
          "--verbosity", "normal",
          "--collect:XPlat Code Coverage",
          "--results-directory", "TestResults"
        )

        dotnet test @dotnetParams

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: TestResults/**/*
        reporter: dotnet-trx        # Format of test results

    - name: Benchmark
      run: |
        $dotnetParams = @(
          "--no-build",
          "--configuration", "${CONFIGURATION}",
          "--project", "benchmarks/StrideTerrainGeneration.Benchmarks/StrideTerrainGeneration.Benchmarks.csproj",
          "--filter", "*",
          "--verbosity", "normal"
        )
        dotnet run @dotnetParams